version: '3.8'

services:
  web:
    build: .
    container_name: neoorrery_web
    command: python NeoOrreryProject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis  # Assuming you're using Redis for Celery; remove if not needed

  redis:
    image: redis:alpine
    container_name: neoorrery_redis
    ports:
      - "6379:6379"
