# Generated by Django 5.1.1 on 2024-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('nasa_id', models.CharField(default='TBD', max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('nasa_id', models.CharField(default='TBD', max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('orbital_period', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('argument_of_periapsis', models.FloatField(blank=True, null=True)),
                ('longitude_of_ascending_node', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('nasa_id', models.CharField(default='TBD', max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('semi_major_axis', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('argument_of_periapsis', models.FloatField(blank=True, null=True)),
                ('longitude_of_ascending_node', models.FloatField(blank=True, null=True)),
                ('mean_anomaly', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
