# Generated by Django 5.1.1 on 2024-09-22 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBodyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_bodies', models.IntegerField(default=0)),
                ('total_planets', models.IntegerField(default=0)),
                ('total_comets', models.IntegerField(default=0)),
                ('total_asteroids', models.IntegerField(default=0)),
                ('total_pha', models.IntegerField(default=0)),
                ('planet_change', models.FloatField(blank=True, null=True)),
                ('comet_change', models.FloatField(blank=True, null=True)),
                ('asteroid_change', models.FloatField(blank=True, null=True)),
                ('pha_change', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
