# Generated by Django 5.1.1 on 2024-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0004_alter_userprofile_profile_picture_nasadatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeCloseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nasa_id', models.CharField(max_length=255)),
                ('distance', models.FloatField(help_text='Distance from Earth in kilometers')),
                ('velocity', models.FloatField(help_text='Velocity in km/h')),
                ('approach_date', models.DateField()),
                ('is_critical', models.BooleanField(default=False)),
            ],
        ),
    ]
