# Generated by Django 5.1.1 on 2024-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0005_realtimecloseapproach'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='critical_distance',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_time_distance',
            field=models.IntegerField(default=100000),
        ),
    ]
