# Generated by Django 5.1.1 on 2024-10-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0007_topic_userprofile_points_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
