# Generated by Django 5.1.1 on 2024-10-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
    ]
